### ISSUE TITLE
Add documentation on using `import-a:drawing` with the Fetch extension

### ISSUE THREAD

**Issue by cienciascontic** [NetLogo/ImportA-Extension#4]
Hi!
I need some help to make this works. I would like to use import-a:drawing in NetLogo web to import a background the same way I do it in NetLogo desktop:
import-drawing "fondo-bosque-telarania.png"

What would be the equivalent set of instructions to make this work the same way as in NetLogo desktop using 'fetch' and 'import-a' extensions?

I've read the examples and tried but I'm confused about how to write the URL of my background file. In NetLogo desktop, my file (as you can see in my code) is placed in the same folder as my NetLogo file. In NetLogo web I can either place it in the same folder of the HTML file or access it through my https URL (in this case "https://recursostic.info/archivos/imagenes/fondo-bosque-telarania.png")

Thanks for your help.
Kind of regards,

Cristián

**Comment by LaCuneta** [comment]
@cienciascontic Sorry you're having trouble with this.  To import an image into the drawing layer in NetLogo Web you want to use the `fetch:url-async` primitive to get the data from your image URL, then you want to provide it a callback anonymous procedure that will take the data and use it with `import-a:drawing`.  

```netlogo
extensions [ fetch import-a ]

to set-drawing
  clear-drawing ; not necessary, just to make clear the load worked
  let image-url "https://ccl.northwestern.edu/netlogo/models/models/Sample%20Models/Biology/Evolution/Bug%20Hunt%20Camouflage.png"
  fetch:url-async image-url [ data -> import-a:drawing data ]  
end
```

But when I try to run that code with your URL on https://netlogoweb.org/launch#NewModel, I get the error "Extension exception: Could not fetch resource from the given URL. Make sure the URL is correct, that there are no network issues, and that CORS access is permitted."  I can see the image loads if I visit the URL directly, so this seems like an issue with Cross-Origin Resource Sharing (CORS).  If you're trying to run your model from netlogoweb.org, then you'll need to adjust your web server's CORS settings to allow netlogoweb.org to remotely fetch files from it.  How to do that will depend on your web host and what software they run, but adjusting these settings is usually a common task.

If you're trying to run a model hosted on the same server as the image, then it might work just with the above code as there is no resource sharing involved.

Also, make sure both the URL and your model are using HTTPS, trying to mix secure and insecure can also cause issues.

I'll use this issue as a reminder to add an example to the documentation here of using `import-a:drawing` with the Fetch extension.

**Comment by cienciascontic** [comment]
Worked perfect placing my background image on the same folder of my HTML NetLogo web file!!
Thanks for your detailed and clean explanation (and also for your willingness in understanding my rudimentary English, haha!!).

**Comment by LaCuneta** [comment]
Great to hear!  I also added a better-documented example to [the `README.md` file](https://github.com/NetLogo/ImportA-Extension#drawing-layer-example).

**Comment by LaCuneta** [comment]
And NetLogo is used all over the world, so we understand English is a second language for many of our users.
